# Generated by Django 2.0.5 on 2018-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20180605_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
